// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChE1DB2CwYMoVzp8Dt6xovOGdSzPNksDI',
    appId: '1:381461947304:web:21576b99926e3e9ced739d',
    messagingSenderId: '381461947304',
    projectId: 'toeigo',
    authDomain: 'toeigo.firebaseapp.com',
    storageBucket: 'toeigo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA1PWswvHCDDVrveXzV6vWcTPZ1MWCCTs',
    appId: '1:381461947304:android:f877e967930b15f7ed739d',
    messagingSenderId: '381461947304',
    projectId: 'toeigo',
    storageBucket: 'toeigo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDmfY7OwV9rROGVR0Bw0QAoSQ7ysTADQQ',
    appId: '1:381461947304:ios:ac46fab5ea5c4c0eed739d',
    messagingSenderId: '381461947304',
    projectId: 'toeigo',
    storageBucket: 'toeigo.firebasestorage.app',
    iosBundleId: 'jp.cloxs.toeigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDmfY7OwV9rROGVR0Bw0QAoSQ7ysTADQQ',
    appId: '1:381461947304:ios:ac46fab5ea5c4c0eed739d',
    messagingSenderId: '381461947304',
    projectId: 'toeigo',
    storageBucket: 'toeigo.firebasestorage.app',
    iosBundleId: 'jp.cloxs.toeigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChE1DB2CwYMoVzp8Dt6xovOGdSzPNksDI',
    appId: '1:381461947304:web:5e6087ed186d9711ed739d',
    messagingSenderId: '381461947304',
    projectId: 'toeigo',
    authDomain: 'toeigo.firebaseapp.com',
    storageBucket: 'toeigo.firebasestorage.app',
  );
}
